import Header from "@/components/layouts/header/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/layouts/footer/footer";
import { cn } from "@/lib/utils";
import { NextThemeProvider } from "@/components/providers/next-theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-[100dvh] flex flex-col")}>
        <NextThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div className="grow flex items-center">{children}</div>
          {/* <Footer /> */}
        </NextThemeProvider>
      </body>
    </html>
  );
}
