import Header from "@/components/layouts/header/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/layouts/footer/footer";
import { getServerSession } from "next-auth";
import { cn } from "@/lib/utils";
import { NextThemeProvider } from "@/components/providers/next-theme-provider";
import NextAuthProvider from "@/components/providers/next-auth-provider";
import { options } from "./api/auth/[...nextauth]/options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-[100dvh] flex flex-col")}>
        <NextAuthProvider session={session} refetchOnWindowFocus={true}>
          <NextThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            <Header />
            <div className="grow flex items-center">{children}</div>
            {/* <Footer /> */}
          </NextThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
